Repository SOLUX-h-APP-y/frontend, pull requests merged in 2025-01, with the labels that each got.

#24 [Feat] MyPostListScreen UI 구현
  src/assets/icons/whiteBackIcon.png
  src/assets/images/sample.png
  src/components/ NavigateHeader.js
  src/components/Buttons.js
  src/components/PostPreviewItem.js
  src/components/Tags.js
  src/navigation/StackNavigator.js
  src/screens/#2_Post/CreatePostScreen.js
  src/screens/#2_Post/MyPostList.js
  src/screens/#2_Post/PostDetailScreen.js
  src/screens/#2_Post/PostListScreen.js
Labels: feat

#25 [Feat] ReviewScreen UI 구현
  src/components/ NavigateHeader.js
  src/components/Buttons.js
  src/components/ChatHeader.js
  src/components/ChatItem.js
  src/components/CustomHeader.js
  src/components/CustomHeaders.js
  src/components/InputFields.js
  src/components/PostHeader.js
  src/components/ToastMessage.js
  src/navigation/StackNavigator.js
  src/screens/#2_Post/CreatePostScreen.js
  src/screens/#2_Post/MyPostList.js
  src/screens/#2_Post/PostDetailScreen.js
  src/screens/#2_Post/PostListScreen.js
  src/screens/#3_Chat/ChatListScreen.js
  src/screens/#3_Chat/ChatScreen.js
  src/screens/#3_Chat/ReviewScreen.js
  src/styles/Chat/ChatHeaderStyles.js
  src/styles/Chat/ChatItemStyles.js
  src/styles/Chat/PostHeaderStyles.js
Labels: feat

#28 [Feat] MypageScreen UI 구현
  babel.config.js
  ios/Podfile.lock
  package-lock.json
  package.json
  src/assets/icons/bellIcon.png
  src/assets/icons/editIcon.png
  src/assets/icons/emptybellIcon.png
  src/assets/images/close.png
  src/assets/images/level_earth.png
  src/assets/images/level_forest.png
  src/assets/images/level_grass.png
  src/assets/images/level_seed.png
  src/assets/images/level_sprout.png
  src/assets/images/level_tree.png
  src/components/Buttons.js
  src/components/CustomHeaders.js
  src/components/LevelProgress.js
  src/components/PostPreviewItem.js
  src/components/ReviewModal.js
  src/components/Tabs.js
  src/components/UserProfile.js
  src/navigation/StackNavigator.js
  src/screens/#4_Mypage/MypageScreen.js
  src/styles/FontStyles.js
Labels: feat

#33 [Feat] EditMypageScreen UI 구현
  ios/Podfile.lock
  ios/h_APP_y/Info.plist
  ios/h_APP_y/PrivacyInfo.xcprivacy
  package-lock.json
  package.json
  src/assets/icons/clearIcon.png
  src/assets/icons/editpencilIcon.png
  src/components/InputFields.js
  src/components/ToastMessage.js
  src/components/UserProfile.js
  src/components/UserProfileImage.js
  src/navigation/StackNavigator.js
  src/screens/#3_Chat/ChatScreen.js
  src/screens/#3_Chat/ReviewScreen.js
  src/screens/#4_Mypage/EditMypageScreen.js
Labels: feat

#35 [Feat] PostDetailScreen Modal UI 구현
  ios/Podfile.lock
  src/assets/icons/closeIcon.png
  src/assets/icons/settingIcon.png
  src/components/StateSelector.js
  src/screens/#2_Post/PostDetailScreen.js
  src/styles/Colors.js
Labels: feat

#36 [Feat] CreatePostScreen Location UI 구현
  ios/Podfile
  ios/Podfile.lock
  ios/h_APP_y/Info.plist
  ios/h_APP_y/PrivacyInfo.xcprivacy
  package-lock.json
  package.json
  src/components/Buttons.js
  src/navigation/StackNavigator.js
  src/screens/#2_Post/CreatePostScreen.js
  src/screens/#2_Post/SetLocationScreen.js
Labels: feat

#39 [Refactoring] handleShowReviews 수정
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/Buttons.js
  src/components/PostPreviewItem.js
  src/screens/#4_Mypage/MypageScreen.js
Labels: refactoring

#44 [Fix] PostPreviewItem Button, Tag 위치 변경
  ios/Podfile.lock
  src/components/PostPreviewItem.js
Labels: fix

#51 [Fix] MypageScreen UI 변경
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/PostPreviewItem.js
  src/components/Tabs.js
  src/screens/#4_Mypage/MypageScreen.js
Labels: fix

#52 [Feat] MypageScreen UI
  src/components/Buttons.js
  src/components/LevelProgress.js
  src/navigation/StackNavigator.js
  src/screens/#4_Mypage/MypageScreen.js
  src/styles/FontStyles.js
Labels: feat

#55 [Feat] SignUp + Location / SignIn / Token관리 구현
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/Buttons.js
  src/components/InputFields.js
  src/navigation/StackNavigator.js
  src/screens/#1_Login/OnboardingScreen.js
  src/screens/#1_Login/SetProfileScreen.js
  src/screens/#2_Post/PostListScreen.js
  src/services/LocationManager.js
  src/services/TokenManager.js
  src/states/UserContext.js
Labels: feat

#57 [Feat] MypageScreen Profile / EditProfile / Cheer 구현
  src/assets/images/defaultProfile.png
  src/components/Buttons.js
  src/components/UserProfile.js
  src/components/UserProfileImage.js
  src/screens/#1_Login/SetProfileScreen.js
  src/screens/#4_Mypage/EditMypageScreen.js
  src/screens/#4_Mypage/MypageScreen.js
  src/services/api.js
Labels: feat

#63 [Fix] Add multipart/for-data for PATCH /profiles/me API
  src/screens/#4_Mypage/EditMypageScreen.js
  src/screens/#4_Mypage/MypageScreen.js
Labels: fix

#67 [Feat] Fetch PostList
  src/assets/icons/setLocationIcon.png
  src/components/Buttons.js
  src/components/CustomHeaders.js
  src/components/InputFields.js
  src/components/OptionPanel.js
  src/components/OptionSelector.js
  src/components/PostPreviewItem.js
  src/screens/#2_Post/PostListScreen.js
Labels: feat

#69 [Feat] Fetch Post Detail
  package-lock.json
  package.json
  src/components/BottomBar.js
  src/components/Buttons.js
  src/components/CustomHeaders.js
  src/components/MiniMap.js
  src/components/OptionSelector.js
  src/components/PostPreviewItem.js
  src/components/StateSelector.js
  src/screens/#1_Login/SetProfileScreen.js
  src/screens/#2_Post/CreatePostScreen.js
  src/screens/#2_Post/PostDetailScreen.js
  src/screens/#2_Post/PostListScreen.js
Labels: feat

#70 [Feat] Create Post
  ios/h_APP_y/Info.plist
  src/components/Buttons.js
  src/components/InputFields.js
  src/components/PostPreviewItem.js
  src/components/StateSelector.js
  src/components/Tags.js
  src/navigation/BottomTabNavigator.js
  src/screens/#1_Login/OnboardingScreen.js
  src/screens/#1_Login/SetProfileScreen.js
  src/screens/#2_Post/CreatePostScreen.js
  src/screens/#2_Post/MyPostList.js
  src/screens/#2_Post/PostListScreen.js
  src/screens/#2_Post/SetLocationScreen.js
  src/screens/#4_Mypage/MypageScreen.js
  src/services/LocationManager.js
Labels: feat

#73 [Feat] Fetch Chat APIs
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/BottomBar.js
  src/components/Buttons.js
  src/components/ChatItem.js
  src/components/CustomHeaders.js
  src/navigation/BottomTabNavigator.js
  src/screens/#2_Post/PostDetailScreen.js
  src/screens/#3_Chat/ChatListScreen.js
  src/screens/#3_Chat/ChatScreen.js
Labels: feat

#76 [Feat] Reupload Post
  src/components/BottomBar.js
  src/components/Buttons.js
  src/components/OptionPanel.js
  src/components/PostPreviewItem.js
  src/screens/#2_Post/CreatePostScreen.js
  src/screens/#2_Post/MyPostList.js
  src/screens/#2_Post/PostDetailScreen.js
  src/screens/#2_Post/PostListScreen.js
Labels: feat
